### ISSUE TITLE
git pullしたからかxcodeが戻っている

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisMatch#6]
大幅変更する前のコミットまで遡ったあとだからかプッシュできなかった。トシになんとかしてもらったが、開くとバージョンがトーナメントとかを入れている大幅変更した後の状態になっていた。もう一回ブランチを切ろうとしてもうまくいかない。どうすればいい？`大幅変更前`というコミットまで戻したい
<img width="574" alt="スクリーンショット 2019-05-31 22 48 41" src="https://user-images.githubusercontent.com/19428366/58710035-661ed180-83f6-11e9-8a1f-ebe45a06c53c.png">

**Comment by tosh7** [comment]
ブランチ切るならコミットしてから、じゃないとブランチきれないかなー！
コミットを巻き戻したいときは、
git reset --hard コミットIDでできる！

**Comment by sotakenmotsu** [comment]
ありがとう、やってみる

**Comment by sotakenmotsu** [comment]
<img width="580" alt="スクリーンショット 2019-05-31 23 02 19" src="https://user-images.githubusercontent.com/19428366/58710833-37095f80-83f8-11e9-9ac6-71303e2a4ef8.png">
これでやり方あってる？プッシュできてないっぽいんだけど

**Comment by tosh7** [comment]
![スクリーンショット 2019-06-01 12 34 30](https://user-images.githubusercontent.com/27297319/58743316-ec283000-8469-11e9-9210-6cf42c8ad784.png)

**Comment by tosh7** [comment]
brunchは切れてるよー

**Comment by tosh7** [comment]
![スクリーンショット 2019-06-01 12 39 13](https://user-images.githubusercontent.com/27297319/58743344-812b2900-846a-11e9-98ac-4f68e194c3e0.png)
![スクリーンショット 2019-06-01 12 39 04](https://user-images.githubusercontent.com/27297319/58743345-81c3bf80-846a-11e9-8b5f-961b45168406.png)

**Comment by tosh7** [comment]
これをみながら戻したいコミットIDを探す感じ

**Comment by sotakenmotsu** [comment]
<img width="580" alt="スクリーンショット 2019-06-02 14 19 28" src="https://user-images.githubusercontent.com/19428366/58757136-7a231a00-8541-11e9-9b84-b69c196405f7.png">
git reset した後にプッシュしようとすると前と同じエラーが出るんだけど、これどうやってなおすの？

**Comment by tosh7** [comment]
https://qiita.com/rch1223/items/9377446c3d010d91399b

**Comment by tosh7** [comment]
この記事を参考にするといいかな！
